// Shared product/category dictionaries and fallback catalog data.
// Loaded before app.js.

const FALLBACK_PRODUCTS = [
    // Зелень и Грибы
    { id: 14, name: "Грибы шампиньоны (пучок)", category: "Зелень и Грибы", price: 3690, sale: false },
    { id: 15, name: "Грибы Эноки (пучок)", category: "Зелень и Грибы", price: 600, sale: false },
    { id: 62, name: "Петрушка (пучок)", category: "Зелень и Грибы", price: 200, sale: false },
    { id: 63, name: "Кинза (пучок)", category: "Зелень и Грибы", price: 320, sale: false },
    { id: 64, name: "Руккола (пучок)", category: "Зелень и Грибы", price: 650, sale: false },
    { id: 65, name: "Шпинат (пучок)", category: "Зелень и Грибы", price: 780, sale: false },
    { id: 66, name: "Мята (пучок)", category: "Зелень и Грибы", price: 500, sale: false },
    { id: 67, name: "Сельдерей (пучок)", category: "Зелень и Грибы", price: 1680, sale: false },
    { id: 69, name: "Зелёный лук (пучок)", category: "Зелень и Грибы", price: 440, sale: false },
    { id: 71, name: "Имбирь (пучок)", category: "Зелень и Грибы", price: 2800, sale: false },
    // Овощи
    { id: 1, name: "Свекла (кг)", category: "Овощи", price: 280, sale: false },
    { id: 2, name: "Тыква (кг)", category: "Овощи", price: 480, sale: false },
    { id: 3, name: "Капуста (кг)", category: "Овощи", price: 280, sale: false },
    { id: 4, name: "Кабачки (кг)", category: "Овощи", price: 1600, sale: false },
    { id: 5, name: "Баклажаны (кг)", category: "Овощи", price: 1780, sale: false },
    { id: 6, name: "Чеснок (кг)", category: "Овощи", price: 2210, sale: false },
    { id: 7, name: "Помидоры розовые (кг)", category: "Овощи", price: 1790, sale: false },
    { id: 8, name: "Помидоры на ветке (кг)", category: "Овощи", price: 1590, sale: false },
    { id: 9, name: "Огурцы Рава (кг)", category: "Овощи", price: 2590, sale: false },
    { id: 10, name: "Огурцы Миринда Иран (кг)", category: "Овощи", price: 1260, sale: false },
    { id: 11, name: "Капуста цветная (кг)", category: "Овощи", price: 1500, sale: false },
    { id: 12, name: "Брокколи (кг)", category: "Овощи", price: 1800, sale: false },
    { id: 13, name: "Капуста пекинская (кг)", category: "Овощи", price: 460, sale: false },
    { id: 16, name: "Перец светофор (кг)", category: "Овощи", price: 1950, sale: false },
    { id: 17, name: "Редька (кг)", category: "Овощи", price: 510, sale: false },
    { id: 18, name: "Черри красный (кг)", category: "Овощи", price: 1900, sale: false },
    { id: 19, name: "Квашеная капуста 300г (кг)", category: "Овощи", price: 600, sale: false },
    { id: 68, name: "Айсберг (кг)", category: "Овощи", price: 2400, sale: false },
    { id: 70, name: "Листья салата (кг)", category: "Овощи", price: 1700, sale: false },
    // Орехи и сухофрукты
    { id: 72, name: "Грецкие орехи чищенные (кг)", category: "Орехи и сухофрукты", price: 5700, sale: false },
    { id: 73, name: "Кешью (кг)", category: "Орехи и сухофрукты", price: 7800, sale: false },
    { id: 74, name: "Кешью жареный (кг)", category: "Орехи и сухофрукты", price: 8250, sale: false },
    { id: 75, name: "Миндаль (кг)", category: "Орехи и сухофрукты", price: 7800, sale: false },
    { id: 76, name: "Макадамия (кг)", category: "Орехи и сухофрукты", price: 4500, sale: false },
    { id: 77, name: "Арахис соленый (кг)", category: "Орехи и сухофрукты", price: 2400, sale: false },
    { id: 78, name: "Арахис жареный (кг)", category: "Орехи и сухофрукты", price: 1800, sale: false },
    { id: 79, name: "Арахис в карамельной глазури (кг)", category: "Орехи и сухофрукты", price: 2850, sale: false },
    { id: 80, name: "Арахис в белой глазури (кг)", category: "Орехи и сухофрукты", price: 2850, sale: false },
    { id: 81, name: "Тыквенные семечки (кг)", category: "Орехи и сухофрукты", price: 3650, sale: false },
    { id: 82, name: "Чернослив (кг)", category: "Орехи и сухофрукты", price: 2700, sale: false },
    { id: 83, name: "Курага (кг)", category: "Орехи и сухофрукты", price: 3450, sale: false },
    { id: 84, name: "Изюм черный (кг)", category: "Орехи и сухофрукты", price: 4500, sale: false },
    { id: 85, name: "Изюм желтый (кг)", category: "Орехи и сухофрукты", price: 3750, sale: false },
    { id: 86, name: "Науат (кг)", category: "Орехи и сухофрукты", price: 1500, sale: false },
    { id: 87, name: "Конфеты фрукты в шоколаде (кг)", category: "Орехи и сухофрукты", price: 4950, sale: false },
    { id: 88, name: "Кедровые орехи 100г (кг)", category: "Орехи и сухофрукты", price: 1800, sale: false },
    { id: 89, name: "Сушеное манго 1кг (шт)", category: "Орехи и сухофрукты", price: 2250, sale: false },
    // Суперфуды и специи
    { id: 90, name: "Семена льна (кг)", category: "Суперфуды и специи", price: 1350, sale: false },
    { id: 91, name: "Семена чиа (кг)", category: "Суперфуды и специи", price: 3750, sale: false },
    { id: 92, name: "Гвоздика 100г (кг)", category: "Суперфуды и специи", price: 1300, sale: false },
    { id: 93, name: "Корица 100г (кг)", category: "Суперфуды и специи", price: 720, sale: false },
    { id: 94, name: "Бадьян 100г (кг)", category: "Суперфуды и специи", price: 975, sale: false },
    // Цитрусы
    { id: 33, name: "Апельсины (кг)", category: "Цитрусы", price: 990, sale: false },
    { id: 34, name: "Мандарины листовые (кг)", category: "Цитрусы", price: 850, sale: false },
    { id: 35, name: "Мандарины королевские листовые (кг)", category: "Цитрусы", price: 940, sale: false },
    { id: 36, name: "Мандарины Марокко (кг)", category: "Цитрусы", price: 1870, sale: false },
    { id: 37, name: "Мандарины Миниола (кг)", category: "Цитрусы", price: 1670, sale: false },
    { id: 38, name: "Мандарины Медовка (кг)", category: "Цитрусы", price: 850, sale: false },
    { id: 39, name: "Мандарины Турция (кг)", category: "Цитрусы", price: 1550, sale: false },
    { id: 47, name: "Грейпфрут (кг)", category: "Цитрусы", price: 1800, sale: false },
    { id: 56, name: "Лайм (кг)", category: "Цитрусы", price: 580, sale: false },
    { id: 57, name: "Лимон Турция (кг)", category: "Цитрусы", price: 2380, sale: false },
    { id: 59, name: "Помело медовое (кг)", category: "Цитрусы", price: 799, sale: false },
    { id: 60, name: "Помело красное (кг)", category: "Цитрусы", price: 1250, sale: false },
    { id: 61, name: "Помело в сумке (кг)", category: "Цитрусы", price: 2100, sale: false },
    // Экзотика
    { id: 32, name: "Бананы (кг)", category: "Экзотика", price: 990, sale: false },
    { id: 43, name: "Хурма Азербайджан (кг)", category: "Экзотика", price: 1290, sale: false },
    { id: 44, name: "Авокадо (шт)", category: "Экзотика", price: 1190, sale: false },
    { id: 45, name: "Ананас (шт)", category: "Экзотика", price: 1250, sale: false },
    { id: 46, name: "Гранат (кг)", category: "Экзотика", price: 2290, sale: false },
    { id: 51, name: "Манго Смайлик (кг)", category: "Экзотика", price: 1100, sale: false },
    { id: 52, name: "Драгон фрут красный (шт)", category: "Экзотика", price: 1800, sale: false },
    { id: 53, name: "Драгон фрут белый (шт)", category: "Экзотика", price: 870, sale: false },
    { id: 54, name: "Киви в сетке (кг)", category: "Экзотика", price: 990, sale: false },
    { id: 55, name: "Кокос с трубочкой (шт)", category: "Экзотика", price: 1870, sale: false },
    { id: 58, name: "Маракуйя 2 шт (шт)", category: "Экзотика", price: 800, sale: false },
    // Яблоки и Груши
    { id: 22, name: "Яблоки Айдаред (кг)", category: "Яблоки и Груши", price: 980, sale: false },
    { id: 24, name: "Яблоки Лимонка (кг)", category: "Яблоки и Груши", price: 990, sale: false },
    { id: 26, name: "Яблоки Салтанат (кг)", category: "Яблоки и Груши", price: 1050, sale: false },
    { id: 28, name: "Яблоки Семиренко (кг)", category: "Яблоки и Груши", price: 980, sale: false },
    { id: 30, name: "Яблоки Черный принц (кг)", category: "Яблоки и Груши", price: 1190, sale: false },
    { id: 48, name: "Груши Дюшес (кг)", category: "Яблоки и Груши", price: 860, sale: false },
    { id: 49, name: "Груши Конференция (кг)", category: "Яблоки и Груши", price: 2090, sale: false },
    { id: 50, name: "Груши Лесная красавица (кг)", category: "Яблоки и Груши", price: 930, sale: false },
    // Ягоды
    { id: 20, name: "Клубника Египет (кг)", category: "Ягоды", price: 1990, sale: false },
    { id: 21, name: "Голубика (кг)", category: "Ягоды", price: 1650, sale: false },
    { id: 40, name: "Виноград Бычий глаз (кг)", category: "Ягоды", price: 1390, sale: false },
    { id: 41, name: "Виноград Хусаин (кг)", category: "Ягоды", price: 1380, sale: false },
    { id: 42, name: "Виноград Шайн мускат (кг)", category: "Ягоды", price: 3800, sale: false },
    { id: 95, name: "Облепиха замороженная (кг)", category: "Ягоды", price: 2500, sale: false },
    { id: 96, name: "Малина замороженная (кг)", category: "Ягоды", price: 5680, sale: false },
    { id: 97, name: "Вишня замороженная (кг)", category: "Ягоды", price: 5700, sale: false },
    { id: 98, name: "Клюква замороженная (кг)", category: "Ягоды", price: 4350, sale: false },
    { id: 99, name: "Смородина замороженная (кг)", category: "Ягоды", price: 5990, sale: false },
];

const CATEGORY_EMOJIS = {
    "Акция": "🔥",
    "Зелень и Грибы": "🌿",
    "Овощи": "🥦",
    "Орехи и сухофрукты": "🥜",
    "Суперфуды и специи": "✨",
    "Цитрусы": "🍊",
    "Экзотика": "🥭",
    "Яблоки и Груши": "🍎",
    "Ягоды": "🍓",
};

const PRODUCT_EMOJIS = {
    "грибы": "🍄", "шампиньон": "🍄", "эноки": "🍄",
    "петрушка": "🌿", "кинза": "🌿", "руккола": "🥬", "шпинат": "🥬",
    "мята": "🌿", "сельдерей": "🥬", "лук": "🧅", "имбирь": "🫚",
    "свекла": "🫒", "тыква": "🎃", "капуста": "🥬", "кабачк": "🥒",
    "баклажан": "🍆", "чеснок": "🧄", "помидор": "🍅", "огурц": "🥒",
    "брокколи": "🥦", "перец": "🫑", "редька": "🫒", "черри": "🍅",
    "квашен": "🥬", "айсберг": "🥬", "салат": "🥬",
    "орех": "🥜", "кешью": "🥜", "миндаль": "🥜", "макадам": "🥜",
    "арахис": "🥜", "семечк": "🌻", "чернослив": "🫐", "курага": "🍑",
    "изюм": "🍇", "науат": "🍬", "конфет": "🍫", "кедров": "🌲",
    "манго": "🥭", "семена": "🌱", "чиа": "🌱",
    "гвоздик": "🌺", "корица": "✨", "бадьян": "⭐",
    "апельсин": "🍊", "мандарин": "🍊", "грейпфрут": "🍊",
    "лайм": "🍋", "лимон": "🍋", "помело": "🍈",
    "банан": "🍌", "хурма": "🍅", "авокадо": "🥑", "ананас": "🍍",
    "гранат": "🫐", "драгон": "🐉", "киви": "🥝", "кокос": "🥥",
    "маракуйя": "💛",
    "яблок": "🍎", "груш": "🍐",
    "клубник": "🍓", "голубик": "🫐", "виноград": "🍇",
    "облепих": "🟠", "малин": "🫐", "вишн": "🍒",
    "клюкв": "🔴", "смородин": "🫐",
    "сушеное": "🥭", "замороженная": "❄️",
};
